[package]
name = "oxc_linter"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_ast = { path = "../oxc_ast" }
oxc_diagnostics = { path = "../oxc_diagnostics" }
oxc_macros = { path = "../oxc_macros" }
oxc_semantic = { path = "../oxc_semantic" }

lazy_static = { workspace = true }
serde_json = { workspace = true }
indextree = { workspace = true }
phf = { version = "0.11", features = ["macros"] }
rustc-hash = { workspace = true }
num-traits = "0.2.15"

[dev_dependencies]
oxc_allocator = { path = "../oxc_allocator" }
oxc_parser = { path = "../oxc_parser" }
insta = { version = "1.14.0", features = ["glob"] }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
